import { AudioManager } from '../engine/AudioManager';
import { GameState } from '../state/GameState';

const chapters = [
  { eyebrow: '01 · CAMINOS Y TERRITORIOS', title: 'Qhapaq Ñan: una red construida por muchos pueblos', text: 'El Qhapaq Ñan articuló comunidades, caminos anteriores al Tawantinsuyu y nuevas obras estatales a través de territorios andinos diversos. Su historia no pertenece a una población homogénea.', question: '¿Qué interpretación respeta mejor esta red?', options: ['Conectó territorios y saberes de distintos pueblos andinos', 'Fue una carretera aislada de una sola ciudad', 'Eliminó todas las identidades locales'], correct: 0 },
  { eyebrow: '02 · AGRICULTURA DE ALTURA', title: 'Andenes, agua y pisos ecológicos', text: 'Los andenes ayudan a conservar suelo y agua y a cultivar en distintas alturas. Las prácticas varían según comunidad, clima, territorio y continuidad local.', question: '¿Por qué no existe una única explicación para todos los andenes?', options: ['Porque responden a territorios, comunidades y épocas diferentes', 'Porque nunca tuvieron función agrícola', 'Porque todos fueron construidos del mismo modo'], correct: 0 },
  { eyebrow: '03 · MEMORIA Y REGISTRO', title: 'Khipus: cuentas, relaciones y memoria', text: 'Los khipus registraron información mediante fibras, colores, torsiones y nudos. Su interpretación requiere combinar ejemplares conservados, arqueología y conocimientos de comunidades andinas.', question: '¿Cuál es la forma más cuidadosa de presentarlos?', options: ['Explicar lo comprobado y señalar lo que sigue en investigación', 'Afirmar que todos significan exactamente lo mismo', 'Tratarlos como objetos decorativos sin información'], correct: 0 }
] as const;

export class AndeanJourneyModal {
  private chapterIndex = 0;
  constructor(private container: HTMLElement, private onBack: () => void) {}
  public show(): void { const saved = Number(localStorage.getItem('ancestria_andean_journey_v1') || 0); this.chapterIndex = Math.min(saved, chapters.length - 1); this.renderOverview(saved); }
  private renderOverview(saved: number): void {
    this.container.innerHTML = `<div class="mexica-journey-overlay"><article class="mexica-journey-window journey-overview-window"><header class="mexica-journey-header"><div><span class="badge">RECORRIDO ANDINO</span><h2>Tres saberes para explorar</h2><p>Elige un capítulo. Tu progreso queda guardado en este dispositivo.</p></div><button class="btn-close" id="andean-close" aria-label="Cerrar">&times;</button></header><div class="journey-overview-grid">${chapters.map((c, i) => `<button class="journey-chapter-card ${i < saved ? 'completed' : ''}" data-andean-chapter="${i}"><span class="journey-number">0${i + 1}</span><span class="culture-status">${c.eyebrow.split('·')[1]}</span><strong>${c.title}</strong><small>${i < saved ? '✓ Memoria recorrida' : i === Math.min(saved, chapters.length - 1) ? 'Continuar aquí →' : 'Explorar capítulo →'}</small></button>`).join('')}</div><footer class="journey-overview-footer">Qhapaq Ñan · Andenes · Khipus</footer></article></div>`;
    this.container.querySelector('#andean-close')?.addEventListener('click', () => { this.close(); this.onBack(); });
    this.container.querySelectorAll<HTMLButtonElement>('[data-andean-chapter]').forEach((button) => button.addEventListener('click', () => { this.chapterIndex = Number(button.dataset.andeanChapter); AudioManager.getInstance().playClick(); this.render(); }));
  }
  private render(feedback = ''): void {
    const c = chapters[this.chapterIndex];
    this.container.innerHTML = `<div class="mexica-journey-overlay"><article class="mexica-journey-window"><header class="mexica-journey-header"><div><span class="badge">RECORRIDO ANDINO</span><h2>${c.title}</h2></div><button class="btn-close" id="andean-close" aria-label="Cerrar">&times;</button></header><div class="mexica-progress"><span style="width:${((this.chapterIndex + 1) / chapters.length) * 100}%"></span></div><div class="mexica-journey-body"><section class="mexica-story"><span class="culture-status">${c.eyebrow}</span><p>${c.text}</p><aside class="source-principle"><strong>Cómo leemos las fuentes</strong><br>Distinguimos pueblos, épocas y territorios. Priorizamos instituciones y voces andinas, y señalamos cuándo una interpretación académica continúa en debate.</aside></section><section class="mexica-activity"><span class="badge">ACTIVIDAD DE MEMORIA</span><h3>${c.question}</h3><div class="mexica-options">${c.options.map((o, i) => `<button data-andean-option="${i}">${o}</button>`).join('')}</div><p class="mexica-feedback" aria-live="polite">${feedback}</p></section></div><footer class="mexica-sources"><span>Voces y fuentes del recorrido:</span><a href="https://qhapaqnan.cultura.pe/" target="_blank" rel="noopener noreferrer">Ministerio de Cultura del Perú · Qhapaq Ñan</a><a href="https://ich.unesco.org/es/RL/conocimientos-tecnicas-y-rituales-vinculados-a-la-renovacion-anual-del-puente-qeswachaka-00594" target="_blank" rel="noopener noreferrer">UNESCO · renovación comunitaria del Q’eswachaka</a><a href="https://bdpi.cultura.gob.pe/" target="_blank" rel="noopener noreferrer">Base de Datos Oficial de Pueblos Indígenas u Originarios del Perú</a><small>El recorrido evita presentar al Tawantinsuyu como sinónimo de todos los pueblos andinos y reconoce continuidades contemporáneas.</small></footer></article></div>`;
    this.container.querySelector('#andean-close')?.addEventListener('click', () => { this.close(); this.onBack(); });
    this.container.querySelectorAll<HTMLButtonElement>('[data-andean-option]').forEach((b) => b.addEventListener('click', () => { AudioManager.getInstance().playClick(); if (Number(b.dataset.andeanOption) !== c.correct) return this.render('Revisa el contexto y vuelve a intentarlo.'); if (this.chapterIndex < chapters.length - 1) { this.chapterIndex++; localStorage.setItem('ancestria_andean_journey_v1', String(this.chapterIndex)); return this.render(); } localStorage.setItem('ancestria_andean_journey_v1', String(chapters.length)); GameState.getInstance().addKnowledgeFragments(30); this.complete(); }));
  }
  private complete(): void { this.container.innerHTML = `<div class="mexica-journey-overlay"><article class="mexica-journey-window mexica-complete"><span class="completion-symbol">✦</span><span class="badge">MEMORIA REGISTRADA</span><h2>Recorrido andino completado</h2><p>Exploraste caminos, agricultura de altura y khipus respetando la diversidad de pueblos, territorios y fuentes.</p><button class="btn-menu-primary" id="andean-finish">Volver a los recorridos</button></article></div>`; this.container.querySelector('#andean-finish')?.addEventListener('click', () => { this.close(); this.onBack(); }); }
  public close(): void { this.container.innerHTML = ''; }
}
