import { AudioManager } from '../engine/AudioManager';
import { PEOPLE_CATALOG, PeopleCatalogEntry, ATLAS_SOURCE_URL } from '../data/peopleCatalog';
import { CultureId } from '../data/types';
import { getLanguage } from '../i18n';

type Chapter = { eyebrow: string; title: string; text: string; question: string; options: string[]; correct: number };

export class PeopleJourneyModal {
  private cultureId: CultureId = 'quechua';
  private chapterIndex = 0;
  private feedback = '';
  constructor(private container: HTMLElement, private onBack: () => void) {}

  public show(cultureId: CultureId): void { this.cultureId = cultureId; this.renderOverview(); }
  private profile(): PeopleCatalogEntry { return PEOPLE_CATALOG.find((item) => item.id === this.cultureId)!; }
  private key(): string { return `ancestria_people_journey_${this.cultureId}_v1`; }
  private saved(): number { return Math.min(Number(localStorage.getItem(this.key()) || 0), 5); }

  private chapters(): Chapter[] {
    const p = this.profile(), lang = getLanguage(), name = p.name[lang], territory = p.territory[lang], languages = p.languages[lang], summary = p.summary[lang];
    if (lang === 'pt-BR') return [
      { eyebrow:'01 · NOME E IDENTIDADE', title:`Como apresentamos ${name}`, text:summary, question:'Qual abordagem evita apagar identidades próprias?', options:[`Usar ${name} com contexto e reconhecer diferenças internas`,'Substituir todos os nomes por uma categoria continental','Tratar povos próximos como uma única cultura'], correct:0 },
      { eyebrow:'02 · TERRITÓRIO', title:'Territórios e relações', text:`Esta ficha situa o percurso em: ${territory}. Território envolve história, relações e presença, não apenas um ponto no mapa.`, question:'Qual território corresponde a esta ficha?', options:['Todo o continente americano sem distinção',territory,'Um território genérico sem relação comunitária'], correct:1 },
      { eyebrow:'03 · LÍNGUAS', title:'Pluralidade linguística', text:`Línguas registradas na ficha: ${languages}. Uma família linguística não torna comunidades culturalmente idênticas.`, question:'O que a ficha informa sobre línguas?', options:['Que somente o espanhol deve ser considerado','Que todas desapareceram no passado',languages], correct:2 },
      { eyebrow:'04 · TEMPO E CONTINUIDADE', title:p.kind==='living'?'Presença contemporânea':'Contexto histórico', text:p.kind==='living'?`${name} possui presença contemporânea; não deve ser apresentado apenas no passado.`:`${name} é apresentado como formação histórica, sem representar sozinho todos os povos atuais relacionados ao território.`, question:'Qual leitura temporal é mais responsável?', options:['Misturar épocas diferentes sem explicação',p.kind==='living'?'Reconhecer presença e vozes contemporâneas':'Explicar a formação histórica e seus limites','Usar uma imagem congelada e homogênea'], correct:1 },
      { eyebrow:'05 · FONTES E RESPONSABILIDADE', title:'Como continuar a pesquisa', text:'O Atlas é um ponto de partida. Conteúdos mais específicos precisam de fontes atuais, situadas e, sempre que possível, produzidas por pessoas e organizações indígenas.', question:'Que fonte deve ter prioridade no aprofundamento?', options:['Uma interpretação colonial isolada','Fontes e perspectivas indígenas específicas, com contexto','Uma descrição genérica sem autoria'], correct:1 }
    ];
    if (lang === 'en') return [
      { eyebrow:'01 · NAME AND IDENTITY', title:`How we present ${name}`, text:summary, question:'Which approach avoids erasing distinct identities?', options:[`Use ${name} in context and recognize internal differences`,'Replace every name with one continental category','Treat neighboring peoples as one culture'], correct:0 },
      { eyebrow:'02 · TERRITORY', title:'Territories and relationships', text:`This profile locates the journey in: ${territory}. Territory involves history, relationships, and presence—not merely a point on a map.`, question:'Which territory matches this profile?', options:['The entire Americas without distinction',territory,'A generic territory without community relationships'], correct:1 },
      { eyebrow:'03 · LANGUAGES', title:'Language plurality', text:`Languages recorded in the profile: ${languages}. Sharing a language family does not make communities culturally identical.`, question:'What does the profile say about languages?', options:['Only English should be considered','Every language disappeared in the past',languages], correct:2 },
      { eyebrow:'04 · TIME AND CONTINUITY', title:p.kind==='living'?'Contemporary presence':'Historical context', text:p.kind==='living'?`${name} has a contemporary presence and must not be confined to the past.`:`${name} is presented as a historical formation and does not stand for every present-day people related to the territory.`, question:'Which temporal reading is more responsible?', options:['Merge different periods without explanation',p.kind==='living'?'Recognize contemporary presence and voices':'Explain the historical formation and its limits','Use one frozen, homogeneous image'], correct:1 },
      { eyebrow:'05 · SOURCES AND RESPONSIBILITY', title:'How research should continue', text:'The Atlas is a starting point. More specific content requires current, situated sources—preferably produced by Indigenous people and organizations.', question:'Which source should receive priority?', options:['One isolated colonial interpretation','Specific Indigenous sources and perspectives, presented in context','A generic description without authorship'], correct:1 }
    ];
    return [
      { eyebrow:'01 · NOMBRE E IDENTIDAD', title:`Cómo presentamos ${name}`, text:summary, question:'¿Qué enfoque evita borrar identidades propias?', options:[`Usar ${name} con contexto y reconocer diferencias internas`,'Sustituir todos los nombres por una categoría continental','Tratar a pueblos próximos como una única cultura'], correct:0 },
      { eyebrow:'02 · TERRITORIO', title:'Territorios y relaciones', text:`Esta ficha sitúa el recorrido en: ${territory}. El territorio implica historia, relaciones y presencia, no solo un punto en el mapa.`, question:'¿Qué territorio corresponde a esta ficha?', options:['Todo el continente americano sin distinción',territory,'Un territorio genérico sin relaciones comunitarias'], correct:1 },
      { eyebrow:'03 · LENGUAS', title:'Pluralidad lingüística', text:`Lenguas registradas en la ficha: ${languages}. Una familia lingüística no vuelve culturalmente idénticas a las comunidades.`, question:'¿Qué informa la ficha sobre las lenguas?', options:['Que solo debe considerarse el español','Que todas desaparecieron en el pasado',languages], correct:2 },
      { eyebrow:'04 · TIEMPO Y CONTINUIDAD', title:p.kind==='living'?'Presencia contemporánea':'Contexto histórico', text:p.kind==='living'?`${name} tiene presencia contemporánea y no debe presentarse solamente en el pasado.`:`${name} se presenta como formación histórica y no representa por sí sola a todos los pueblos actuales relacionados con el territorio.`, question:'¿Qué lectura temporal es más responsable?', options:['Mezclar épocas distintas sin explicación',p.kind==='living'?'Reconocer presencia y voces contemporáneas':'Explicar la formación histórica y sus límites','Usar una imagen congelada y homogénea'], correct:1 },
      { eyebrow:'05 · FUENTES Y RESPONSABILIDAD', title:'Cómo continuar la investigación', text:'El Atlas es un punto de partida. Los contenidos específicos requieren fuentes actuales, situadas y, siempre que sea posible, producidas por personas y organizaciones indígenas.', question:'¿Qué fuente debe tener prioridad?', options:['Una interpretación colonial aislada','Fuentes y perspectivas indígenas específicas y contextualizadas','Una descripción genérica sin autoría'], correct:1 }
    ];
  }

  private labels() { const l=getLanguage(); return l==='es'?{badge:'RECORRIDO EDUCATIVO',title:'Cinco memorias para explorar',intro:'Elige un capítulo. Tu progreso queda guardado en este dispositivo.',done:'✓ Memoria recorrida',go:'Explorar capítulo →',activity:'ACTIVIDAD DE MEMORIA',right:'Respuesta contextualizada.',wrong:'Revisa el contexto e inténtalo de nuevo.',back:'Volver a los recorridos',sources:'Fuente panorámica del recorrido'}:l==='pt-BR'?{badge:'PERCURSO EDUCATIVO',title:'Cinco memórias para explorar',intro:'Escolha um capítulo. Seu progresso fica salvo neste dispositivo.',done:'✓ Memória percorrida',go:'Explorar capítulo →',activity:'ATIVIDADE DE MEMÓRIA',right:'Resposta contextualizada.',wrong:'Revise o contexto e tente novamente.',back:'Voltar aos percursos',sources:'Fonte panorâmica do percurso'}:{badge:'LEARNING JOURNEY',title:'Five memories to explore',intro:'Choose a chapter. Progress is saved on this device.',done:'✓ Memory explored',go:'Explore chapter →',activity:'MEMORY ACTIVITY',right:'Contextualized answer.',wrong:'Review the context and try again.',back:'Back to journeys',sources:'Journey overview source'}; }

  private renderOverview(): void {
    const chapters=this.chapters(), saved=this.saved(), labels=this.labels(), p=this.profile(), lang=getLanguage();
    this.container.innerHTML=`<div class="mexica-journey-overlay"><article class="mexica-journey-window journey-overview-window"><header class="mexica-journey-header"><div><span class="badge">${labels.badge} · ${p.name[lang]}</span><h2>${labels.title}</h2><p>${labels.intro}</p></div><button class="btn-close" id="people-journey-close">&times;</button></header><div class="journey-overview-grid">${chapters.map((c,i)=>`<button class="journey-chapter-card ${i<saved?'completed':''}" data-people-chapter="${i}"><span class="journey-number">0${i+1}</span><span class="culture-status">${c.eyebrow.split('·')[1]}</span><strong>${c.title}</strong><small>${i<saved?labels.done:labels.go}</small></button>`).join('')}</div><footer class="journey-overview-footer">${p.territory[lang]} · ${p.languages[lang]}</footer></article></div>`;
    this.container.querySelector('#people-journey-close')?.addEventListener('click',()=>this.closeBack());
    this.container.querySelectorAll<HTMLButtonElement>('[data-people-chapter]').forEach(btn=>btn.addEventListener('click',()=>{this.chapterIndex=Number(btn.dataset.peopleChapter);this.feedback='';this.renderChapter();}));
  }
  private renderChapter(): void {
    const chapters=this.chapters(), c=chapters[this.chapterIndex], labels=this.labels(), order=[0,1,2].sort(()=>Math.random()-.5), progress=((this.chapterIndex+1)/5)*100;
    this.container.innerHTML=`<div class="mexica-journey-overlay"><article class="mexica-journey-window"><header class="mexica-journey-header"><div><span class="badge">${labels.badge}</span><h2>${c.title}</h2></div><button class="btn-close" id="people-journey-close">&times;</button></header><div class="mexica-progress"><span style="width:${progress}%"></span></div><div class="mexica-journey-body"><section class="mexica-story"><span class="culture-status">${c.eyebrow}</span><p>${c.text}</p><aside class="source-principle">${this.profile().summary[getLanguage()]}</aside></section><section class="mexica-activity"><span class="badge">${labels.activity}</span><h3>${c.question}</h3><div class="mexica-options">${order.map(i=>`<button data-people-option="${i}">${c.options[i]}</button>`).join('')}</div><p class="mexica-feedback">${this.feedback}</p></section></div><footer class="mexica-sources"><span>${labels.sources}:</span><a href="${ATLAS_SOURCE_URL}" target="_blank" rel="noopener noreferrer">Atlas sociolingüístico UNICEF / FUNPROEIB Andes</a></footer></article></div>`;
    this.container.querySelector('#people-journey-close')?.addEventListener('click',()=>this.renderOverview());
    this.container.querySelectorAll<HTMLButtonElement>('[data-people-option]').forEach(btn=>btn.addEventListener('click',()=>{const correct=Number(btn.dataset.peopleOption)===c.correct;AudioManager.getInstance().playInteract();this.feedback=correct?`✓ ${labels.right}`:labels.wrong;if(correct){const saved=Math.max(this.saved(),this.chapterIndex+1);localStorage.setItem(this.key(),String(saved));if(this.chapterIndex<4){this.chapterIndex++;this.feedback='';this.renderChapter();}else this.renderOverview();}else this.renderChapter();}));
  }
  private closeBack():void{this.container.innerHTML='';this.onBack();}
}
